name: owlmarket_qa_connect
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  auto_size_text: ^3.0.0
  csv: ^5.0.2
  data_table_2: ^2.4.2
  dio: ^5.1.1
  excel: ^2.1.0
  file_picker: ^5.2.11
  firebase_core: ^2.11.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  go_router: ^7.0.0
  gsheets: ^0.4.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.8.1
  logging: ^1.1.1
  tuple: ^2.0.1
  mailer: ^6.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.3.3
  build_runner: ^2.0.5
  json_serializable: ^6.6.2
  hive_generator: ^2.0.0


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/csv/
